// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skzilrtxdqripwnrqqhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNremlscnR4ZHFyaXB3bnJxcWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTUyMjMsImV4cCI6MjA2MjM3MTIyM30.lqkarEuQdUyHSGCMfYHOsaj6wSglWi6n1iyqXel2plE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);